### ISSUE TITLE
Some problems playing mp3 and youtube videos

### ISSUE THREAD

**Issue by anika200** [herecura/opera-ffmpeg-codecs#2]
There are some problems playing mp3 files as documented here [https://forum.manjaro.org/t/opera-mp3-mp4/23443/15]
Is this something that would have to do with the tools you are providing for us?

**Comment by BlackIkeEagle** [comment]
What version of opera do you have, I have no issues
- opera 45.0.2552.635
- opera-ffmpeg-codecs 58.0.3029.81

I don't know what you mean with "Is this something that would have to do with the tools you are providing for us?"

I provide binary packages for opera in the community repo and alongside I provide the opera-ffmpeg-codecs in my own repo, those versions match to ensure playback of these proprietary stuff

**Comment by BlackIkeEagle** [comment]
You can also comment to https://forum.manjaro.org/t/opera-mp3-mp4/23443/22, what heavy dependencies, opera-ffmpeg-codecs only depends on glibc so I suspect this user means the build dependencies

**Comment by anika200** [comment]
The original question was to mean that I was unsure if the binary package you provide had anything to do with the issues pointed to in the thread I linked. I have not had any problems here either but some folks obviously have problems playing files that use codecs from the binary package.

Here is really the question then, are you aware of any issures or current bugs with the codecs used in the package?

**Comment by BlackIkeEagle** [comment]
No I'm not aware of any issues, *But* users must make sure the versions match.

If they want more support they must provide better and more detailed information, not just "It does not work anymore"

What WM/DE is used, is there hw accel available, ...

**Comment by anika200** [comment]
" But users must make sure the versions match" 
Forgive my ignorance, what versions of what files must be matching?
For example on my working system of Manjaro Testing I have Opera 45.0.2552.635 and 
opera-ffmpeg-codecs  58.0.3029.81-1 from repository herecura, what should be matching or expected.

Yes I understand more info could/should be given but so far I have not narrowed the problem to codecs or DE or what.

**Comment by BlackIkeEagle** [comment]
opera://gpu/ could be usefull in some cases, maybe its graphics drivers, I'm also not sure

**Comment by BlackIkeEagle** [comment]
Also if someone could just post the pages where something is not working it might become easier

simple test page: https://www.quirksmode.org/html5/tests/video.html (these should all play fine)
more extended test page: http://tools.woolyss.com/html5-audio-video-tester/

**Comment by anika200** [comment]
Thank you for the time I appreciate the effort.
I think the guys on that thread can not even play mp3 stream Audio no Video is involved, I may be wrong but the thread at manjaro forums is really about audio (exception is the last poster). 
Please see the top of thread post #3 I think has the links to failing sound and then I provide follow up audio that works for me but not them.

**Comment by BlackIkeEagle** [comment]
FYI in comment 15 https://forum.manjaro.org/t/opera-mp3-mp4/23443/15 you don't need ffmpeg and ffmpeg2.8, only opera-ffmpeg-codecs

**Comment by BlackIkeEagle** [comment]
maybe if someone could post the output of `pacman -Qs opera-ffmpeg-codecs`

**Comment by anika200** [comment]
Apparently the problem is solved moving the file /usr/lib/opera/extra_lib/libffmpeg.so to /usr/lib/opera/libffmpeg.so. 
I noted in the manjaro forum thread that one file was half the size of the other??? So maybe some corrupt file somewhere?? not sure.... 
Anyway thank you for your time and help.

**Comment by BlackIkeEagle** [comment]
Maybe opera is sometimes too picky to get the correct libffmpeg.so. Well if its fixed now its ok for me.
