### ISSUE TITLE
Stopped working since 46.0.2597.32 update

### ISSUE THREAD

**Issue by chupasaurus** [herecura/opera-ffmpeg-codecs#3]
Greetings!
Even though there were no changes to Chromium version, new Opera update doesn't load properly a library built by you on my PC.
Please check if it works fine or there is a problem on my side.

**Comment by BlackIkeEagle** [comment]
hi  @chupasaurus everything seems to work just fine on my machine. I have opera-46.0.2597.32-1  opera-ffmpeg-codecs-59.0.3071.86-1, Did you install the codecs from my repo or build them from AUR?

**Comment by chupasaurus** [comment]
@BlackIkeEagle I'm using Debian 9, tried both binary package from your repo and AUR build, codecs worked on previous version (Opera 46.0.2597.26, library builded from AUR).

**Comment by BlackIkeEagle** [comment]
I don't know what's different between arch and debian then

**Comment by chupasaurus** [comment]
Found problem, different location for library on my system.
Sorry for overreacting.
